export const COLLECTIONS = [
  "Frontend",
  "Backend",
  "Databases",
  "DevOps",
  "Artificial Intelligence",
  "Mobile Development",
  "Desktop Development",
  "Game Development",
  "Programming Languages",
  "Security",
  "Testing",
  "Git & Collaboration",
  "Software Architecture",
  "UI / UX",
  "Tools",
  "Career",
  "Algorithms & Computer Science",
  "Networking",
  "Operating Systems",
] as const;
